### ISSUE TITLE
Do dodania ;p

### ISSUE THREAD

**Issue by MichixYT** [NotroDev/VisualText#1]
1. Udostępnić src
2. Dodać możliwość posiadania kilka plików na raz
3. Zapis plików co literkę i po ponownym włączeniu otwarcie tamtych plików
4. Automatyczne przydzielanie składni przez rozszerzenie otwartego pliku
5. Dodanie ciemnego motywu oraz własną customizację
6. Zrobić ładniejsze UI

**Comment by NotroDev** [comment]
Hej! Dzięki za propozycje 😀 Oto odpowiedzi na każde pytanie:

1. Kod źródłowy będzie udostępniony gdy program wyjdzie z wersji Alpha.
2. Tak, dodam to, już wpiszę do mojego todo.
3. Aktualnie edytor pyta, czy użytkownik chce zapisać, jeśli chce wyjść z niepustym tekstem, ale mogę to dodać.
4. Aktualnie nie ma żadnego podświetlania składni, za niedługo się za to wezmę i mam auto wykrywanie języka w planach.
5. Ciemny motyw jest już gotowy, potrzeba tylko kilku poprawek.
6. Napisz co zmienić, a przemyślę to.

Oto moje todo, aby ominąć niektóre możliwe pytania: https://trello.com/b/V8o2FhmU/visualtext-todo

Miłego dnia :)
